/**
 * SVG → pptxgenjs shapes converter.
 *
 * Parses a simple SVG (generated by diagram-svg.ts) and emits
 * pptxgenjs addShape / addText calls with precise coordinates.
 *
 * Only handles the Phase C core subset: <rect>, <text>, <g transform="translate()">.
 * SVG coordinates are in inches; slotOffset is added to position within the slide.
 */

interface SlotOffset {
  x: number;
  y: number;
}

interface PptxSlide {
  addShape(name: string, opts: Record<string, unknown>): void;
  addText(text: unknown, opts: Record<string, unknown>): void;
}

// ── Simple XML Tokenizer (no deps) ────────────────────────

interface SvgRectAttrs {
  x: number;
  y: number;
  width: number;
  height: number;
  fill: string;
  stroke: string;
  strokeWidth: number;
}

interface SvgTextAttrs {
  x: number;
  y: number;
  fontSize: number;
  fill: string;
  fontFamily: string;
  fontWeight: string;
  textAnchor: string;
  dataW: number;
  content: string;
}

function parseAttr(tag: string, name: string): string {
  const re = new RegExp(`${name}="([^"]*)"`, 'i');
  const m = tag.match(re);
  return m ? m[1] : '';
}

function parseNum(tag: string, name: string, fallback = 0): number {
  const v = parseAttr(tag, name);
  const n = Number.parseFloat(v);
  return Number.isNaN(n) ? fallback : n;
}

function stripHash(color: string): string {
  return color.startsWith('#') ? color.slice(1) : color;
}

/** Parse all <rect> elements from SVG string */
function parseRects(svg: string): SvgRectAttrs[] {
  const results: SvgRectAttrs[] = [];
  const re = /<rect\s[^>]*\/>/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(svg)) !== null) {
    const tag = m[0];
    results.push({
      x: parseNum(tag, 'x'),
      y: parseNum(tag, 'y'),
      width: parseNum(tag, 'width'),
      height: parseNum(tag, 'height'),
      fill: stripHash(parseAttr(tag, 'fill')),
      stroke: stripHash(parseAttr(tag, 'stroke')),
      strokeWidth: parseNum(tag, 'stroke-width', 0),
    });
  }
  return results;
}

/** Parse all <text>...</text> elements from SVG string */
function parseTexts(svg: string): SvgTextAttrs[] {
  const results: SvgTextAttrs[] = [];
  const re = /<text\s([^>]*)>([^<]*)<\/text>/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(svg)) !== null) {
    const attrs = m[1];
    const content = m[2]
      .replace(/&amp;/g, '&')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/&quot;/g, '"');
    const tag = `<text ${attrs}/>`;
    results.push({
      x: parseNum(tag, 'x'),
      y: parseNum(tag, 'y'),
      fontSize: parseNum(tag, 'font-size', 0.12),
      fill: stripHash(parseAttr(tag, 'fill')),
      fontFamily: parseAttr(tag, 'font-family').split(',')[0].trim(),
      fontWeight: parseAttr(tag, 'font-weight') || 'normal',
      textAnchor: parseAttr(tag, 'text-anchor') || 'start',
      dataW: parseNum(tag, 'data-w', 0),
      content,
    });
  }
  return results;
}

// ── Public API ─────────────────────────────────────────────

/**
 * Render parsed SVG elements onto a pptxgenjs slide.
 * @param slide - pptxgenjs slide object
 * @param svgString - SVG generated by compileDiagramToSvg
 * @param offset - slot position (x, y) to offset all coordinates
 */
export function renderSvgToSlide(slide: PptxSlide, svgString: string, offset: SlotOffset): void {
  // Render rects as shapes
  for (const r of parseRects(svgString)) {
    slide.addShape('rect', {
      x: r.x + offset.x,
      y: r.y + offset.y,
      w: r.width,
      h: r.height,
      fill: { color: r.fill },
      line: r.stroke ? { color: r.stroke, width: r.strokeWidth * 72 } : undefined,
    });
  }

  // Render texts
  for (const t of parseTexts(svgString)) {
    const fontSizePt = t.fontSize * 72;
    const align = t.textAnchor === 'middle' ? 'center' : 'left';
    const textW = t.dataW > 0 ? t.dataW : 4;
    // For center-aligned text, position the box so anchor is at center
    const textX = align === 'center' ? t.x - textW / 2 : t.x;
    slide.addText(
      [
        {
          text: t.content,
          options: {
            fontFace: t.fontFamily,
            fontSize: fontSizePt,
            color: t.fill,
            bold: t.fontWeight === 'bold',
          },
        },
      ],
      {
        x: textX + offset.x,
        y: t.y + offset.y - t.fontSize * 0.8,
        w: textW,
        h: t.fontSize * 1.3,
        align,
        valign: 'middle',
        margin: 0,
        wrap: false,
      },
    );
  }
}
